### ISSUE TITLE
Wrong decompilation of function call parameters

### ISSUE THREAD

**Issue by rfalke** [BoomerangDecompiler/boomerang#122] opened 2018-10-29 06:26 UTC
Version: ed7a3e1
Exe: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/output/ia32_elf/subject.exe
Source:
```
int intermediate_2_parameter_names(int arg)
{
        char *n;
        char *m;
        if (arg == 1) {
                n = "/is/a/1";
        } else {
                n = "/is/something/else";
        }
        if (arg >= 0) {
                m = "r";
        } else {
                m = "w";
        }
        if (!fopen(n, m)) {
                puts("failed");
        }
        return 0;
}
```

Output:

```
/** address: 0x08048960 */
void intermediate_2_parameter_names(__size32 param1)
{
    FILE *eax_1;                // r24{4}

    if (param1 != 1) {
    }
    eax_1 = fopen("/is/a/1", "r");
    if (eax_1 == 0) {
        puts("failed");
    }
    return;
}
```

* The if-block is empty
* There should be code paths to pass different parameters to the fopen call

**Comment by ceeac** [comment] 2018-10-30 18:56
This is caused by missing semantics for the `cmovs` instruction and will be fixed as part of #69.

**Closed** 2019-01-14 10:40 UTC
Labels: type: bug
