### ISSUE TITLE
Assertion 'sect' failed

### ISSUE THREAD

**Issue by TambourineReindeer** [BoomerangDecompiler/boomerang#59] opened 2016-04-29 14:17 UTC
When I try to decompile a certain Linux elf executable, I get SIGABRT and this error:

```
boomerang: /home/razzy/Desktop/boomerang/loader/elf/ElfBinaryFile.cpp:277: virtual bool ElfBinaryFile::RealLoad(const QString&): Assertion `sect' failed.
```

Since the executable is from a commercial video game (Teleglitch), I'm not sure how to have others test it :/ The Windows executable works fine, however, and decompiles to completion.

**Comment by nemerle** [comment] 2016-04-29 16:48
This is likely caused by the failure of this check
```cpp
     if(SectionMap.find(interval<ADDRESS>::right_open(from,to))!=SectionMap.end()) {
        return nullptr;
    }
```
And this check fails when trying to create a section that overlaps with existing one.
What might help in tracking the problem down is posting output from ```objdump -h EXECUTABLE_NAME```

**Comment by TambourineReindeer** [comment] 2016-04-29 18:16
Before I go to bed, here you go:
[objdump.txt](https://github.com/nemerle/boomerang/files/242986/objdump.txt)
Hope it helps for now!

**Comment by nemerle** [comment] 2016-04-29 19:05
At a glance the sections look OK, and should be read properly by boomerang. I've tried running boomerang on teleglitch linux demo and it did not crash on that, so must be some difference between demo and release executables.

**Comment by TambourineReindeer** [comment] 2016-04-30 08:27
Oh, I can try checking it myself (Is it the Gamefront download?). I wonder if something changed between the game at the original release and the "Die More Edition" update.

**Comment by TambourineReindeer** [comment] 2016-04-30 09:35
Hmm..I tried running the Linux demo through Boomerang and had another assertion failure (subExp1). I attached console output from Boomerang:
[output_teleglitch32_demo.txt](https://github.com/nemerle/boomerang/files/243527/output_teleglitch32_demo.txt)

Here is the output again from the full release (with the latest version of Boomerang; when I posted this issue I was using one from a few weeks ago):
```
Not adding 0 sized section  ""
Segment ".strtab" would intersect existing one ".interp"
boomerang: /media/razzy/Storage/Projects/Source Codes/Disassembly/boomerangc/loader/elf/ElfBinaryFile.cpp:252: virtual bool ElfBinaryFile::LoadFromMemory(QByteArray&): Assertion `sect' failed.
```
So as you said, there is a section overlapping with another.

**Comment by ceeac** [comment] 2018-09-07 09:17
This should be fixed in the current develop version, so I'm closing this.

**Closed by ceeac** 2018-09-07 09:17 UTC
